# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Bindings for normal mode
config.unbind('d')
config.bind('gb', 'back')
config.bind('gf', 'forward')
config.bind('gh', 'open https://start.duckduckgo.com')
config.unbind('r')
config.bind('rr', 'reload')
config.bind('t0', 'tab-focus 10')
config.bind('t1', 'tab-focus 1')
config.bind('t2', 'tab-focus 2')
config.bind('t3', 'tab-focus 3')
config.bind('t4', 'tab-focus 4')
config.bind('t5', 'tab-focus 5')
config.bind('t6', 'tab-focus 6')
config.bind('t7', 'tab-focus 7')
config.bind('t8', 'tab-focus 8')
config.bind('t9', 'tab-focus 9')
config.bind('tc', 'tab-close')
config.bind('tn', 'tab-clone;; open https://start.duckduckgo.com')
config.bind('tr', 'tab-prev')
config.bind('tsr', 'tab-move 1')
config.bind('tsz', 'tab-move -1')
config.bind('tz', 'tab-next')
